// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteAllData() {
  return window['go']['main']['App']['DeleteAllData']();
}

export function GetChatDates() {
  return window['go']['main']['App']['GetChatDates']();
}

export function GetImportedFiles() {
  return window['go']['main']['App']['GetImportedFiles']();
}

export function GetMessagesByDate(arg1) {
  return window['go']['main']['App']['GetMessagesByDate'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SearchKeyword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchKeyword'](arg1, arg2, arg3, arg4);
}
