// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckOllama():Promise<boolean>;

export function DeleteAllData():Promise<void>;

export function GetChatDates():Promise<Array<string>>;

export function GetImportedFiles():Promise<Array<string>>;

export function GetMessagesByDate(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetSettings():Promise<config.Settings>;

export function ImportFiles(arg1:Array<string>):Promise<void>;

export function OpenFileDialog():Promise<Array<string>>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<main.SearchResult>;

export function SearchKeyword(arg1:string,arg2:number,arg3:string,arg4:string):Promise<main.KeywordResult>;
